(source gnu)
(source melpa)
(source marmalade)
(source SC)
(source org)

(depends-on "init-loader")
(depends-on "e2wm")
(depends-on "helm")
(depends-on "popup")
(depends-on "auto-complete")
(depends-on "undo-tree")
(depends-on "zenburn-theme")
(depends-on "anzu")
(depends-on "web-mode")
(depends-on "rainbow-delimiters")
(depends-on "rainbow-mode")
(depends-on "flycheck")
(depends-on "flycheck-pos-tip")
(depends-on "fringe-helper")
(depends-on "git-gutter+")
(depends-on "powerline")
(depends-on "popwin")
(depends-on "smartparens")
(depends-on "undohist" :git "https://github.com/m2ym/undohist-el.git")
(depends-on "volatile-highlights")
(depends-on "smooth-scroll")
(depends-on "ruby-mode")
(depends-on "ruby-block")
(depends-on "ruby-electric")
(depends-on "rinari")
(depends-on "jazzradio" :git "https://github.com/syohex/emacs-jazzradio.git")
(depends-on "php-mode")
(depends-on "php-completion"
        :git "https://github.com/suzuki/php-completion.git"
        :branch "develop"
        :files ("*.el" "phpcmp-index-of-*"))