(source gnu)
(source melpa)
(source marmalade)
(source SC)
(source org)

(depends-on "init-loader")
(depends-on "e2wm")
(depends-on "helm")
(depends-on "popup")
(depends-on "auto-complete")
(depends-on "undo-tree")
(depends-on "zenburn-theme")
(depends-on "anzu")
(depends-on "web-mode")
(depends-on "rainbow-delimiters")
(depends-on "rainbow-mode")
(depends-on "flycheck")
(depends-on "flycheck-pos-tip")
(depends-on "fringe-helper")
(depends-on "git-gutter")
(depends-on "git-gutter-fringe")
(depends-on "powerline")
(depends-on "popwin")
(depends-on "smartparens")
(depends-on "undohist" :git "https://github.com/m2ym/undohist-el.git")
